services:
  - type: web
    name: apparent-temp-bot
    env: python
    region: oregon  # 서울리전 없으면 US 서부 기본
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    plan: free
    branch: main
    autoDeploy: true
